sudo: required

env:
  global:
  - secure: HBFYeB+BJUirImKI0zeqjlb87Ji8cUy0481sKA1Q4WWB0Eq9aNF+9s/YWHiC5MzVS3fbiZdIyHGhH4VU570osiQjwLig8230fFlVy9hiH+AZBgO8E8q/wdWlmZ9abfuxwN6LJGVNKgplRcenC++O2V/YlsIYZ2mqwNtlLzrb4ZwDp1+BLTIFUNh6mrTr6++5ih3vVPYFolHFsbaHO7pWZ72t0r7JXuyBGN1B64HCW9JWgyD2Bg7jruTETUrJ0gUmWDh054xetnP7kRx0KUtOwFcIcS9RgDvNAdgOeeokiSp4q7LaXn9h0YRL1X99Lkhn5LnfYcWuLjk0ZZhOcTtt7IipaFubH1IFEki462t1jzOabYo1EMnZcnHe1qP5YBqTZdlGIrW5sAbA798Wj4q5F7OPCb7JfGcXad3JIHWnTZJw/vJcuBWiwZSIlfhbw4rM7KNrqXdbtgaGEflDrpv1wHghjsTjzY9vb0Ssxl0TPPiobfk+wxL5dfJVtOP+h9dOJ2KSS9Cwbw+RXJL3Dx67CHF0ZURkpOIh3Y9bW0Z+PE41X14BQRiUbvR35L6e2MLB6bCoR4kCpWiE08zadfMEHH7r413d2EEKawJVWBvCHdYoLz9bI8smXITaE4JwIpegd5dByJMtVkM6LS1xnBSjYTjHrwcwOpDgKAjd+7+yDzo=
  - secure: rRIR3pIrVPcAUYkOZB4d/h7dMM1UL+75xvkuG+yKsDBArnGcJgFnm/NYwUkBCmzaI85YRTz0y36TOskyx0AXYzL5LKByrOGcvxkURIvTHIynzV9Z9WNmzBRvohVNNr+vdaZH0/mASlDGIkrVXAV8vi212pR8fKLbVxRur20jxAJtHHhL/1qpTnQL27J7x0g0eAUAfb8AyGtSWjODq+gHHqL/tBXd3tsLditmrwC4h9PUtapC2XJagLMTvPPnrpCe2zr/5smeqUn6kBqiz3UQ6tXAo7DR4Wg5DaYvuOE+IsrHxeELSWOz7Jq7o+w4eN59cqV1nptvxSzu5KLTqLb1E/18p6gZ6FjVZeHeSOqG8AUhfow0nY5C5yreq4eH2wIRRDCGDZBJtTDBqStA18u5QYGcGgN0tVTTozNrB2SER2NK/MHZ4eJJo9s4oUftIaegFdAY/LPvkBccelhLhkdcjj1lUJSVDNHfOCwFP4Di2FPt2fvKYInakqFrUpTSkp7ILzuVN5dg81hErmdNKSB3FWREeLcx5GOEO6+5NTHFFgrQgJO20mRVou9kNu5VfAVw/cs+kmibsJHTD4JtctaN8dn/81zB1abrP3mMC003Hcy9eFkClwkXtVQEq/EtvFrMEAm6Bazjudmpvwx3jJNwEcR3IliE6b17X/EXibh0iAE=

services:
- docker

language: go

go:
- 1.10.x

script:
- make all
- docker build -t datareply/alertmanager-sns-forwarder:latest .

before_deploy:
- mkdir releases
- tar -zcf releases/alertmanager-sns-forwarder-darwin_amd64.tar.gz bin/darwin/alertmanager-sns-forwarder
- tar -zcf releases/alertmanager-sns-forwarder-linux_amd64.tar.gz bin/linux/alertmanager-sns-forwarder
- tar -zcf releases/alertmanager-sns-forwarder-windows_amd64.tar.gz bin/windows/alertmanager-sns-forwarder

deploy:
  provider: releases
  api_key:
    secure: nlzFy12uilNNc+Hvzu7nQzraoyi5FtjYAn9u7OYFpzR/Ek6WkdS011dooPXLFAjQacZSlRvwt7aogB7ox9a5K0uIfLe/ZKQ2EOZyPZNZPylixI8deMFT+O8s2G8mPjNAZakQCLo5bibcSXbNw1e44at8VltB3dshWQLB1mLATLraUfKx85NtiQmSHTR7d0DDzxI0YXTHY3qgJulYm+gF6k7OqAd9+V5JfsVgfa+6v0kuXhjvR6QSYb5NvP9W0mWmd6gHOKCUugTFpk5kDB9W+id2CNilphPWL5FvF38zRaVPjzy8iTEvslEvi9X32QeQcuDYc3gEBvj1LZLdBow0x+AgXECLm0guv/wlrUFlPjh1IqPA4npPsDYM6Fi9/z/HjwGW4FU6zQjTo3C1e5cO9V1G03m7LUwkh1ZmU8demp3VAbKEpVasSMmxZoWt2K5e9bsZAB/Va9jzoANKejWBGxtkVBFmTEgTSGAOcCk4Y2XTU8rFD3MZLk7uMT4MPg1Y9zlT1cII1OSVSxkzS/cWDy7mrUfZTzrzk3ZIKCd04tw7ocU2ZPGAXCvKnFimoBg79EyME3zUX8CzRW7sehZxLSYE4+UHeSGLsaWxhIjoEPH26tBz8yzp+2wLCaYsCRUF7Et0ehWvlFGXkTaUz7YOnWtscbaeJf5ZgGGlc6XbIjw=
  file:
    - "releases/alertmanager-sns-forwarder-darwin_amd64.tar.gz"
    - "releases/alertmanager-sns-forwarder-linux_amd64.tar.gz"
    - "releases/alertmanager-sns-forwarder-windows_amd64.tar.gz"
  skip_cleanup: true
  on:
    tags: true
    repo: DataReply/alertmanager-sns-forwarder
    branch: master

after_success:
  - test $TRAVIS_TAG && 
    docker tag datareply/alertmanager-sns-forwarder:latest datareply/alertmanager-sns-forwarder:$TRAVIS_TAG &&
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && 
    docker push datareply/alertmanager-sns-forwarder:$TRAVIS_TAG
  - test $TRAVIS_BRANCH = "master" && 
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && 
    docker push datareply/alertmanager-sns-forwarder
